// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuWQsK-g6CLgB68pIKWRxvEXXhYktFIeg',
    appId: '1:624218622942:web:67f6d100b7b64979cd2b4f',
    messagingSenderId: '624218622942',
    projectId: 'datingapp-v2',
    authDomain: 'datingapp-v2.firebaseapp.com',
    storageBucket: 'datingapp-v2.firebasestorage.app',
    measurementId: 'G-5L4RX64K4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1Dmv_H__VTwpg11XI1if9JFQc0gOnaQ',
    appId: '1:624218622942:android:7b803e60ce6cd300cd2b4f',
    messagingSenderId: '624218622942',
    projectId: 'datingapp-v2',
    storageBucket: 'datingapp-v2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Aqor5gxj_j0nuoTu0TuuewxYVqf_D9Y',
    appId: '1:624218622942:ios:87dbe126551969f8cd2b4f',
    messagingSenderId: '624218622942',
    projectId: 'datingapp-v2',
    storageBucket: 'datingapp-v2.firebasestorage.app',
    iosBundleId: 'com.example.datingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuWQsK-g6CLgB68pIKWRxvEXXhYktFIeg',
    appId: '1:624218622942:web:b8f25004075a65d4cd2b4f',
    messagingSenderId: '624218622942',
    projectId: 'datingapp-v2',
    authDomain: 'datingapp-v2.firebaseapp.com',
    storageBucket: 'datingapp-v2.firebasestorage.app',
    measurementId: 'G-PP6TT9B3WL',
  );
}
